AllCops:
  TargetRubyVersion: 2.2
Style/Documentation:
  Enabled: false
  Exclude:
    - lib/attributor/flatpack/version.rb
    - lib/attributor/flatpack.rb
    - lib/attributor/flatpack/config.rb
    - lib/attributor/flatpack/config_dsl_compiler.rb
    - lib/attributor/flatpack/undefined_key.rb
Metrics/MethodLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Style/RedundantSelf:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
