AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Layout/LineLength:
  Max: 160
  Exclude:
    - "spec/**/*.rb"
Style/RedundantSelf:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
Style/RedundantFetchBlock:
  Enabled: false
Style/HashEachMethods:
  Enabled: false
